#!/bin/bash -l

# Script to compile and start the ML repository server
# so that the FVT tests (or other tests) can be run
# against the service.

buildprofiles=""
profiles="--activate-profiles run-local"
mvnopts=
opts="-DskipTests=true"
clusteropts=

while [[ $# -gt 0 ]]; do
    # -debug
    if [[ "$1" == -d* ]]; then
        profiles="--activate-profiles debug-local"
        shift
    fi

    # -tests
    if [[ "$1" == -t* ]]; then
        opts=
        shift
    fi

    # -verbose
    if [[ "$1" == -v* ]]; then
        set -x
        shift
    fi

    # -offline
    if [[ "$1" == -o* ]]; then
        mvnopts="$mvnopts $1"
        shift
    fi

    # -U
    if [[ "$1" == "-U" ]]; then
        mvnopts="$mvnopts $1"
        shift
    fi

    # -fae
    if [[ "$1" == "-fae" ]]; then
        mvnopts="$mvnopts $1"
        shift
    fi

    # -cluster
    if [[ "$1" == -c* ]]; then
        shift
        clusteropts="-Dextra.local.jvm.args=-Dservice.wml.host=$1 -Dservice.wml.port=443 -Dservice.wml.private.host=$1 -Dservice.wml.private.port=443"
        shift
    fi
done

set -x

mvn ${mvnopts} ${profiles} ${clusteropts}
